<a href="https://colab.research.google.com/github/shubh28012004/solving-linear-equations-in-python/blob/main/Linear_Algebra_in_Python_(PDS_1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Pandas is the library that is used to make array **

In [3]:
import numpy as np
import matplotlib.pyplot as plt

 **Inializing Array**

In [4]:
a = np.array([1,2,3])
print(a.shape) #printnp.shape(a)

(3,)


In [6]:
b = np.array([[1,2,3],[5,6,7]]) #2D array
print(b.shape)

(2, 3)


**NumPy Array Stacking**

In [9]:
x = np.array([[1,2,3]])
y = np.array([[4,5,6]])
print(np.hstack((x,y)))
print(np.hstack((x,y)).shape)
print(np.vstack((x,y)))
print(np.vstack((x,y)).shape)


[[1 2 3 4 5 6]]
(1, 6)
[[1 2 3]
 [4 5 6]]
(2, 3)


**3D Array**

In [12]:
k = np.array([[[1,2,3],[4,5,6]],[[3,4,5],[7,8,9]]]) # (2 - no of blocks , 2 - no of rows , 3 - no of columns )
print(k.shape)
print(k)

(2, 2, 3)
[[[1 2 3]
  [4 5 6]]

 [[3 4 5]
  [7 8 9]]]


There are three 2D Array in image having 3 channel -  **RGB**

**Dot Product**

In [14]:
A=np.array([[1,2,3]])
B=np.array([[4,5,6]])
print(A.shape)
print(B.shape)

result = np.dot(A,B.T) #Dot product  (b.t TRANSPOSE OF B )
print(result)

(1, 3)
(1, 3)
[[32]]


In [19]:
A = np.array([[1,2],[3,4]])
B = np.array([[7,5],[2,3]])
print(np.inner(A,B))  # ALSO WE CAN USE np.dot(A,B)
print(np.dot(A,B.T))
print(np.matmul(A,B))

[[17  8]
 [41 18]]
[[17  8]
 [41 18]]
[[11 11]
 [29 27]]


**FOR NORMAL MULTIPLICATION**

In [20]:
A = np.array([[1,2],[3,4]])
B = np.array([[7,5],[2,3]])
print(np.matmul(A,B))
print(np.dot(A,B))

[[11 11]
 [29 27]]
[[11 11]
 [29 27]]


**Matric Inverse**

In [21]:
from numpy.linalg import inv
a=np.array([[1,2],[3,4]] # Determine for taking out inverse should be non zero so we will take a matrix of any order rather than 1
ainv = inv(a)
print(ainv)

[[-2.   1. ]
 [ 1.5 -0.5]]


**Determinant of a 2D Array **

In [23]:
A = np.array([[1,7],[6,9]])
print(np.linalg.det(A))

-33.0


**Linear Algebra Model**
Here's a sample dataset



In [31]:
X=np.array([[1,2],[1,3],[1,4],[1,5],[1,6]])
Y=np.array([60,75,82,90,95])

H=inv(np.dot(X.T,X)) #H is MOORE PENROSE INVERSE
theta = np.dot(np.dot(H,X.T),Y) #or
theta = np.linalg.lstsq(X,Y)[0] # [0] is done to avoid tuples
print(theta)

[46.4  8.5]


<ipython-input-31-b8f3b171d9f8>:6: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  theta = np.linalg.lstsq(X,Y)[0] # [0] is done to avoid tuples


Solve system of linear eqns

In [29]:
A=np.array([[2,4],[6,8]])
B=np.array([5,6])

#solve the system of linear eqns as Ax=B
x=np.linalg.solve(A,B)
print(x)

[-2.    2.25]


Norms and distances in python

In [33]:
import numpy as np
a=np.array([1,2,3])
euclidiean_form = np.linalg.norm(a)
print("Euclidiean norm " , euclidiean_form)

Euclidiean norm  3.7416573867739413


In [34]:
b = np.array([[1,2],[3,4]])
l2_form = np.linalg.norm(b)
print("Euclidiean norm " , l2_form)

Euclidiean norm  5.477225575051661


Distance between 2 points

In [35]:
from scipy.spatial import distance  #scientific python library
import numpy as np
#compute the l2 form between 2 points
point1 = np.array([1,2,3])
point2=np.array([4,5,6])
euclidean_distance = distance.euclidean(point1,point2)
print("Euclidean distance is ",euclidean_distance )

Euclidean distance is  5.196152422706632


In [36]:
manhattan_distance = distance.cityblock(point1,point2)
print("Manhattan ditance : ",manhattan_distance)

Manhattan ditance :  9


Cosine distance between 2 vectors

In [38]:
vector1 = np.array([1,2,3])
vector2 = np.array([4,5,6])
cosine_distance = distance.cosine(vector1,vector2)
print("Cosine direction : " , cosine_distance)

Cosine direction :  0.0253681538029239
